config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 	 resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  before_destroy :remove_file  
  belongs_to :user

  has_attached_file :image, styles: {large: "1024x768", medium: "720x240", thumb: "240x240" },
   :convert_options => {
    :thumb => "-quality 75 -strip" },
    :s3_protocol => :https,
    :storage => :s3,
    :s3_host_name => "s3-sa-east-1.amazonaws.com",
  :s3_credentials => {
      :bucket => ENV['S3_BUCKET_NAME'],
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
      :region => ENV['AWS_REGION']
    }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 250 }
  validates :image, presence: true

  def getImage
    @doc = Nokogiri::HTML(self.content)
    if (!@doc.css('img').blank?)
      @file = @doc.css('img')[0]['src']
      @dir = File.expand_path("..", @file)
      return @dir
    end
  end

  def remove_file
    if !getImage.blank?
      FileUtils.rm_rf(Rails.root.join('public', getImage[1..-1]))
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, :except => [:index, :show,]
	before_action :find_post, only: [:show, :update, :edit, :destroy]

	def index
		@posts = Post.all.order("created_at DESC")	
	end

	def new
		@post = Post.new	
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post, notice: "Post created correctly"
		else
			render 'new'
		end
	end
	
	def show
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else 
			render 'edit'
		end
	end	

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :user_id, :image)
	end

	def find_post
		@post = Post.find(params[:id])		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
	    options = {
	      filter_html:     true,
	      hard_wrap:       true,
	      link_attributes: { rel: 'nofollow', target: "_blank" },
	      space_after_headers: true,
	      fenced_code_blocks: true
	    }
	     extensions = {
	     	autolink: true,
	     	superscript: true,
	     	no_intra_emphasis: true,
	     	highlight: true,
	     	no_styles: false,
	     	lax_spacing: true,
	     	strikethrough: true,
	     	underline: true,
	     	footnotes: true,
	     	tables: true,
	     	disable_indented_code_blocks: false
	    }
	    
	    renderer = Redcarpet::Render::HTML.new(options)
	    markdown = Redcarpet::Markdown.new(renderer, extensions)
	    markdown.render(text).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog | Posts </title>
    <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
	<link rel="icon" type="image/png" sizes="16x16" href="favicon.ico">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <body>
 	<div class="hero is-medium is-dark is-bold">
 	  <nav class="navbar">
 	    <div class="container">
 	      <div class="navbar-brand">
 	        <%= link_to 'Home Blog', posts_path, class: "navbar-item" %>
 	        <% if current_user %>
 	        <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "navbar-item" %>
 	        <% else %>
 	        <%= link_to 'Iniciar Sesión', new_user_session_path, class: "navbar-item" %>
 	        <% end %>
          <%= link_to "Crear Publicación", new_post_path, class:"navbar-item" %>
 	      </div> 	      
 	    </div>
 	  </nav>
 	</div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="column container is-three-fifths">
	<%= simple_form_for @post, html: { multipart: true } do |f| %>
	<div class="field">
		<div class="control">
			<%= f.input :title, input_html: {class: 'input '}, wrapper: false, label_html: {class: 'label'} %>
		</div>
	</div>
	<div class="fiel">
		<div class="control">
			<label class="label"> Portada | 720x240 | </label>
			<%= f.file_field :image %>
		</div>
	</div>
	<div class="field">
		<div class="control">
			<%= f.input :content, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'} %>
		</div>
	</div>
	<%= f.hidden_field :user_id, value: current_user[:id] %>
	<%= f.button :submit, class: "button is-primary" %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/nav' %>
<% content_for :page_title, "Edit Post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "Publicaciones" %>
<%= render 'shared/nav' %>

<% @posts.each do |post| %>
<div class="container">
	<br>
	<div class="card">
  <header class="card-header">
    <h2 class="title card-header-title">
      <%= link_to post.title, post %>
    </h2>
  </header>

  <div class="card-content">  	
    <%= markdown(post.content.first(250) + '...') %>  
    <div class="content"> 
      <time>
      	<small>
        <b>Publicó <i><%= post.user.email %></i> hace 
      	<% time_post = ((Time.now - post.created_at) / 1.hour).round %>
    		  <% if time_post < 25 %>
    		  	<%= "#{time_post} horas" %>
    	 	   <% else %>
    		  	<%= "#{(time_post / 24 ).round} días" %>
    		  <% end %>
        </b>
		    </small>		
      </time>
    </div>
  </div>

  <footer class="card-footer">
	<% if signed_in? && post.user == current_user %>
	<%= link_to 'Nueva Publicación', new_post_path, class: "card-footer-item item1" %>
    <%= link_to 'Editar', edit_post_path(post), class: "card-footer-item item2" %>
    <%= link_to 'Eliminar', post_path(post), method: :delete, data: {confirm: '¿Estás Seguro?' }, class: "card-footer-item item3" %>
    <% else %>
    <%= link_to 'Leer Más', post, class: "card-footer-item item1" %>
    <% end %>
  </footer>
</div>
<br>
</div>
<% end %>

app/views/posts/new.html.erb
<% content_for :page_title, 'Nueva Publicación' %>
<%= render 'shared/nav' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<section>
	<div class="container is-centered">
		<figure class="image is-3by1">
			<%= link_to @post do %>
			<%= image_tag @post.image.url(:medium) %>
			<% end %>
			<figure>
			</div>
</section>

<section class="section">
			<div class="container">
				<% if signed_in? && @post.user == current_user %>
				<nav class="level">
					<div class="level-left">
						<p class="level-item">
							<strong>Actions</strong>
						</p>
					</div>
					<div class="level-right">
						<p class="level-item">
							<%= link_to "Edit", edit_post_path(@post), class: "button" %>
						</p>
						<p class="level-item">
							<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?" }, class: "button is-danger" %>			
						</p>
					</div>
					<% end %>
				</nav>	

				<div class="content box">
					<p class="is-uppercase is-size-2 has-text-centered"><%= @post.title %></p>
					<%= markdown(@post.content)%>
				</div>	
			</div>	
</section>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<section class="hero is-medium is-warning is-bold">
	  <div class="hero-body">
	    <div class="container has-text-centered">
	      <h1 id="titulo" class="title is-1">
			<%= render 'shared/alerts' %>
	        <%= yield :page_title %>
	      </h1>
	    </div>
	  </div>
</section> 